server:
  port: 8181

broker:
  host: localhost
  port: 61616
  username: artemis
  password: artemis

management:
  endpoint:
    health:
      show-details: always
    loggers:
      enabled: true


