server:
  port: 8181

broker:
  host: localhost
  port: 61616
  username: artemis
  password: artemis

management:
  endpoint:
    health:
      show-details: always
    loggers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health, info
  info:
    env:
      enabled: true
info:
  application:
    name: @project.name@
    description: @project.description@
    version: '@project.version@'


